show_on:
  default: top_menu
  type: enum
  choices:
    - top_menu
    - homepage
    - discovery
    - all
  description: top_menu refers to the <a href="/admin/site_settings/category/all_results?filter=top_menu">top menu site setting</a>

plugin_outlet:
  default: "above-main-container"
  type: enum
  choices:
    - above-main-container
    - discovery-above
  description: |
    Select the plugin outlet where the search banner should appear:
    - `above-main-container`: Displays above the main container
    - `below-site-header`: Displays below the site header
    - `discovery-above`: Displays in the discovery-above outlet, ideal for placement at the top of the discovery page

background_image_light:
  type: upload
  default: ""
  description: Background image for the banner on light color palettes

background_image_dark:
  type: upload
  default: ""
  description: Background image for the banner on dark color palettes

tile_background_image: false

show_for:
  default: everyone
  type: enum
  choices:
    - everyone
    - logged_in
    - logged_out

special_style:
  default: "basic style (default)"
  type: enum
  description: Optional variations that change the appearance of the search banner
  choices:
    - "big search, no text"
    - "basic style (default)"
